package autentificación.Interfaces;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import autentificación.conexion.logica;
import autentificación.conexion.logica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Alumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alumno
     */
    public Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        Label_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        Label_Apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        Label_Grado = new javax.swing.JLabel();
        txt_Grado = new javax.swing.JTextField();
        Label_sexo = new javax.swing.JLabel();
        Btn_ingreso = new javax.swing.JButton();
        Btn_Registro = new javax.swing.JButton();
        Panel_titulo = new javax.swing.JDesktopPane();
        txt_titulo = new javax.swing.JLabel();
        Rd_Msculino = new javax.swing.JRadioButton();
        Rd_femeninio = new javax.swing.JRadioButton();

        Label_nombre.setText("Nombre");

        Label_Apellido.setText("Apellido");

        Label_Grado.setText("Grado");

        Label_sexo.setText("Sexo");

        Btn_ingreso.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Btn_ingreso.setText("INGRESO");
        Btn_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ingresoActionPerformed(evt);
            }
        });

        Btn_Registro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Btn_Registro.setText("NUEVO");
        Btn_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistroActionPerformed(evt);
            }
        });

        txt_titulo.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_titulo.setText("Ingrese los datos del usuario");

        Panel_titulo.setLayer(txt_titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Panel_tituloLayout = new javax.swing.GroupLayout(Panel_titulo);
        Panel_titulo.setLayout(Panel_tituloLayout);
        Panel_tituloLayout.setHorizontalGroup(
            Panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_titulo)
                .addGap(77, 77, 77))
        );
        Panel_tituloLayout.setVerticalGroup(
            Panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_tituloLayout.createSequentialGroup()
                .addComponent(txt_titulo)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        Rd_Msculino.setText("Masculino");
        Rd_Msculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rd_MsculinoActionPerformed(evt);
            }
        });

        Rd_femeninio.setText("Femenino");
        Rd_femeninio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rd_femeninioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_titulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_nombre)
                    .addComponent(Label_Apellido)
                    .addComponent(Label_Grado)
                    .addComponent(Label_sexo))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_ingreso)
                        .addGap(69, 69, 69)
                        .addComponent(Btn_Registro))
                    .addComponent(txt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(txt_nombre)
                    .addComponent(txt_Grado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Rd_femeninio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rd_Msculino, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Apellido)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Grado)
                    .addComponent(txt_Grado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_sexo)
                    .addComponent(Rd_femeninio)
                    .addComponent(Rd_Msculino))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ingreso)
                    .addComponent(Btn_Registro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ingresoActionPerformed
        // TODO add your handling code here:
        logica conec= new logica();
            int rs=0;
           
            String nombre= this.txt_nombre.getText();
            String apellido=this.txt_apellido.getText();
            String grado=this.txt_Grado.getText();
         //   String sexo=this.jTextField5.getText();
            String sql="insert into  alumno(nombre,apellido,grado,sexo)values('"+nombre+"','"+apellido+"','"+grado+"')";
        try {
            rs=conec.InsertarGeneralSQL(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        }
            if(rs==1)
            {
                JOptionPane.showMessageDialog(null,"El registro se insertó con éxito");
              this.Btn_ingreso.setEnabled(false);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Problemas al insertar el registro");
            }

    }//GEN-LAST:event_Btn_ingresoActionPerformed

    private void Btn_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistroActionPerformed
        // TODO add your handling code here:
          
      this.txt_nombre.setText(null);
      this.txt_apellido.setText(null);
      this.txt_Grado.setText(null);
     
      this.Btn_ingreso.setEnabled(true);

    }//GEN-LAST:event_Btn_RegistroActionPerformed

    private void Rd_MsculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rd_MsculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rd_MsculinoActionPerformed

    private void Rd_femeninioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rd_femeninioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rd_femeninioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Registro;
    private javax.swing.JButton Btn_ingreso;
    private javax.swing.JLabel Label_Apellido;
    private javax.swing.JLabel Label_Grado;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JLabel Label_sexo;
    private javax.swing.JDesktopPane Panel_titulo;
    public javax.swing.JRadioButton Rd_Msculino;
    public javax.swing.JRadioButton Rd_femeninio;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JTextField txt_Grado;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
