package autentificación.Interfaces;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import autentificación.conexion.logica;
import autentificación.conexion.logica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Alumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alumno
     */
    public Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        panelprincipal = new javax.swing.JPanel();
        Label_nombre = new javax.swing.JLabel();
        Label_Apellido = new javax.swing.JLabel();
        txt_Grado = new javax.swing.JTextField();
        Label_Grado = new javax.swing.JLabel();
        Btn_Registro = new javax.swing.JButton();
        Btn_ingreso = new javax.swing.JButton();
        txt_apellido = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Rd_femeninio = new javax.swing.JRadioButton();
        Rd_Msculino = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Registrar alumnos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/autentificación/Imagenes/icons8-cuadrado-redondeado-24.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(530, 410));
        setMinimumSize(new java.awt.Dimension(530, 410));
        setPreferredSize(new java.awt.Dimension(530, 410));
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_nombre.setForeground(new java.awt.Color(25, 52, 152));
        Label_nombre.setText("Nombre");
        panelprincipal.add(Label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 70, 30));

        Label_Apellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Apellido.setForeground(new java.awt.Color(25, 52, 152));
        Label_Apellido.setText("Apellido");
        panelprincipal.add(Label_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txt_Grado.setBackground(new java.awt.Color(255, 255, 255));
        txt_Grado.setForeground(new java.awt.Color(25, 52, 152));
        txt_Grado.setBorder(null);
        panelprincipal.add(txt_Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 274, 27));

        Label_Grado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Grado.setForeground(new java.awt.Color(25, 52, 152));
        Label_Grado.setText("Grado");
        panelprincipal.add(Label_Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        Btn_Registro.setBackground(new java.awt.Color(25, 52, 152));
        Btn_Registro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_Registro.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Registro.setText("NUEVO");
        Btn_Registro.setBorder(null);
        Btn_Registro.setBorderPainted(false);
        Btn_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistroActionPerformed(evt);
            }
        });
        panelprincipal.add(Btn_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 100, 40));

        Btn_ingreso.setBackground(new java.awt.Color(25, 52, 152));
        Btn_ingreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ingreso.setText("CREAR");
        Btn_ingreso.setBorder(null);
        Btn_ingreso.setBorderPainted(false);
        Btn_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ingresoActionPerformed(evt);
            }
        });
        panelprincipal.add(Btn_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 40));

        txt_apellido.setBackground(new java.awt.Color(255, 255, 255));
        txt_apellido.setForeground(new java.awt.Color(25, 52, 152));
        txt_apellido.setBorder(null);
        panelprincipal.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 274, 25));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setForeground(new java.awt.Color(25, 52, 152));
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        panelprincipal.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 270, 27));

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(25, 52, 152));
        txt_titulo.setText("Registrar alumno");
        panelprincipal.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(25, 52, 152));
        panelprincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 270, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(25, 52, 152));
        panelprincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 270, 20));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(25, 52, 152));
        panelprincipal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 270, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(25, 52, 152))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        Rd_femeninio.setBackground(new java.awt.Color(255, 255, 255));
        Sexo.add(Rd_femeninio);
        Rd_femeninio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rd_femeninio.setForeground(new java.awt.Color(25, 52, 152));
        Rd_femeninio.setText("Femenino");
        Rd_femeninio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rd_femeninioActionPerformed(evt);
            }
        });
        jPanel1.add(Rd_femeninio, new java.awt.GridBagConstraints());

        Rd_Msculino.setBackground(new java.awt.Color(255, 255, 255));
        Sexo.add(Rd_Msculino);
        Rd_Msculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rd_Msculino.setForeground(new java.awt.Color(25, 52, 152));
        Rd_Msculino.setText("Masculino");
        Rd_Msculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rd_MsculinoActionPerformed(evt);
            }
        });
        jPanel1.add(Rd_Msculino, new java.awt.GridBagConstraints());

        panelprincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 370, 70));

        getContentPane().add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 550, 410));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(25, 52, 152));
        jSeparator4.setOpaque(true);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 270, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ingresoActionPerformed
        // TODO add your handling code here:
        logica conec= new logica();
            int rs=0;
           
            String nombre= this.txt_nombre.getText();
            String apellido=this.txt_apellido.getText();
            String grado=this.txt_Grado.getText();
            String sexo ;
            if (this.Rd_femeninio.getModel().isSelected()){
           sexo= "Femenino" ;
            }else {
            sexo=  "Masculino" ;
            } ;  
                    
                  
    
            //   String sexo=this.jTextField5.getText();
            String sql="insert into  alumno(nombre,apellido,grado,sexo)values('"+nombre+"','"+apellido+"','"+grado+"','"+sexo+"')";
        try {
            rs=conec.InsertarGeneralSQL(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Alumno.class.getName()).log(Level.SEVERE, null, ex);
        }
            if(rs==1)
            {
                JOptionPane.showMessageDialog(null,"El registro se insertó con éxito");
              this.Btn_ingreso.setEnabled(false);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Problemas al insertar el registro");
            }

    }//GEN-LAST:event_Btn_ingresoActionPerformed

    private void Btn_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistroActionPerformed
        // TODO add your handling code here:
          
      this.txt_nombre.setText(null);
      this.txt_apellido.setText(null);
      this.txt_Grado.setText(null);
     
      this.Btn_ingreso.setEnabled(true);

    }//GEN-LAST:event_Btn_RegistroActionPerformed

    private void Rd_MsculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rd_MsculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rd_MsculinoActionPerformed

    private void Rd_femeninioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rd_femeninioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rd_femeninioActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Registro;
    private javax.swing.JButton Btn_ingreso;
    private javax.swing.JLabel Label_Apellido;
    private javax.swing.JLabel Label_Grado;
    private javax.swing.JLabel Label_nombre;
    public javax.swing.JRadioButton Rd_Msculino;
    public javax.swing.JRadioButton Rd_femeninio;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JTextField txt_Grado;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
