package autentificación.Interfaces;

import autentificación.Interfaces.Menu;
import autentificación.conexion.ingreso;
import autentificación.conexion.logica;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class inicio extends javax.swing.JFrame {
   int xMouse,yMouse;
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        PanelBarraSuperior = new javax.swing.JPanel();
        Btn_Salir = new javax.swing.JButton();
        PanelForm = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Input_Usuario = new javax.swing.JTextField();
        Separador_usuario = new javax.swing.JSeparator();
        Label_clave = new javax.swing.JLabel();
        Input_password = new javax.swing.JPasswordField();
        Separador_Calve = new javax.swing.JSeparator();
        Btn_ingresar = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();
        PanelImagen = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo-basico-java-swing");
        setBackground(new java.awt.Color(243, 241, 245));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(740, 500));
        setName("Login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(740, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(740, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(187, 187, 187));
        Login.setOpaque(false);
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBarraSuperior.setOpaque(false);
        PanelBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelBarraSuperiorMouseDragged(evt);
            }
        });
        PanelBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBarraSuperiorMousePressed(evt);
            }
        });
        PanelBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Salir.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_Salir.setForeground(new java.awt.Color(25, 52, 152));
        Btn_Salir.setText("X");
        Btn_Salir.setToolTipText("Cerrar programa");
        Btn_Salir.setBorder(null);
        Btn_Salir.setBorderPainted(false);
        Btn_Salir.setContentAreaFilled(false);
        Btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Salir.setDefaultCapable(false);
        Btn_Salir.setFocusPainted(false);
        Btn_Salir.setFocusable(false);
        Btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_SalirMouseExited(evt);
            }
        });
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });
        PanelBarraSuperior.add(Btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, -1));

        Login.add(PanelBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 40));

        PanelForm.setBackground(new java.awt.Color(25, 52, 152));
        PanelForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelForm.setPreferredSize(new java.awt.Dimension(370, 500));
        PanelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("USUARIO");
        PanelForm.add(Label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Input_Usuario.setBackground(new java.awt.Color(25, 52, 152));
        Input_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Input_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Input_Usuario.setText("Ingresa tu nombre de usuario");
        Input_Usuario.setBorder(null);
        Input_Usuario.setOpaque(false);
        Input_Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_UsuarioFocusGained(evt);
            }
        });
        Input_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Input_UsuarioMousePressed(evt);
            }
        });
        Input_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_UsuarioActionPerformed(evt);
            }
        });
        PanelForm.add(Input_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, -1));

        Separador_usuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelForm.add(Separador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 10));

        Label_clave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_clave.setForeground(new java.awt.Color(255, 255, 255));
        Label_clave.setText("CLAVE");
        PanelForm.add(Label_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Input_password.setBackground(new java.awt.Color(25, 52, 152));
        Input_password.setForeground(new java.awt.Color(204, 204, 204));
        Input_password.setText("********");
        Input_password.setBorder(null);
        Input_password.setOpaque(false);
        Input_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_passwordFocusGained(evt);
            }
        });
        Input_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Input_passwordMousePressed(evt);
            }
        });
        Input_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_passwordActionPerformed(evt);
            }
        });
        PanelForm.add(Input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, -1));

        Separador_Calve.setBackground(new java.awt.Color(255, 255, 255));
        PanelForm.add(Separador_Calve, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 10));

        Btn_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btn_ingresar.setForeground(new java.awt.Color(25, 52, 152));
        Btn_ingresar.setText("INGRESAR");
        Btn_ingresar.setToolTipText("Ingresar al programa ");
        Btn_ingresar.setBorder(null);
        Btn_ingresar.setBorderPainted(false);
        Btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_ingresar.setDefaultCapable(false);
        Btn_ingresar.setFocusPainted(false);
        Btn_ingresar.setVerifyInputWhenFocusTarget(false);
        Btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseExited(evt);
            }
        });
        Btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ingresarActionPerformed(evt);
            }
        });
        PanelForm.add(Btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 30));

        TITULO.setBackground(new java.awt.Color(255, 255, 255));
        TITULO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("INICIO DE SESIÓN");
        PanelForm.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        Login.add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        PanelImagen.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagen.setForeground(new java.awt.Color(255, 255, 255));
        PanelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autentificación/Imagenes/undraw_book_lover_mkck.png"))); // NOI18N
        imagen.setLabelFor(imagen);
        imagen.setMaximumSize(new java.awt.Dimension(370, 500));
        imagen.setMinimumSize(new java.awt.Dimension(370, 500));
        imagen.setPreferredSize(new java.awt.Dimension(370, 500));
        imagen.setRequestFocusEnabled(false);
        imagen.setVerifyInputWhenFocusTarget(false);
        PanelImagen.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Login.add(PanelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 570));

        getAccessibleContext().setAccessibleDescription("Ejemplo basico e java swing  en cual se realiza una conexion con una base de datos mysql ,un sencillo login , un crud para crear y eliminar alumnos, una sencilla calculadora y un apartado para calcula la circunferencia y una calculadora sencilla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
System.exit(0);

        
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ingresarActionPerformed
    ResultSet rs=null;
    String user="";
    String pass="";
    
        String usuario =this.Input_Usuario.getText();
        String clave = String.valueOf(this.Input_password.getPassword());
         logica conec=new logica();    
        String sql ="select * from usuario where usuario='"+usuario+"' and  clave ='"+clave+"'";
        
        try {
            rs=conec.ConsultaGeneralSQL(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs.next())//si existan datos
            {
                user=rs.getString(2);
                pass=rs.getString(3);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        ingreso ingreso= new ingreso();
        if
                (usuario.equalsIgnoreCase(user)  && clave.equalsIgnoreCase(pass))
        {
            Menu menu = new Menu();
            menu.setVisible(true);
      this.setVisible(false);
      
        }
        else
        {
                JOptionPane.showMessageDialog(this,"usuario o clave incorrectos");
        }
        
    }//GEN-LAST:event_Btn_ingresarActionPerformed

    private void Input_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_UsuarioActionPerformed

    private void Btn_SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SalirMouseEntered
          Btn_Salir.setForeground(new Color(255, 20, 20));
    }//GEN-LAST:event_Btn_SalirMouseEntered

    private void Input_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_passwordActionPerformed

    private void PanelBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraSuperiorMousePressed
       xMouse = evt.getX();
         yMouse = evt.getY();
    }//GEN-LAST:event_PanelBarraSuperiorMousePressed

    private void PanelBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraSuperiorMouseDragged
    int  x= evt.getXOnScreen();
    int  y= evt.getYOnScreen();
        this.setLocation(x-xMouse,y- yMouse);
    }//GEN-LAST:event_PanelBarraSuperiorMouseDragged

    private void Btn_SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SalirMouseExited
       Btn_Salir.setForeground(new Color(25,52,152));
    }//GEN-LAST:event_Btn_SalirMouseExited

    private void Btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseEntered
     Btn_ingresar.setBackground(new Color (25,52,152));
       Btn_ingresar.setForeground(Color.white);
    }//GEN-LAST:event_Btn_ingresarMouseEntered

    private void Btn_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseExited
      Btn_ingresar.setForeground(new Color (25,52,152));
       Btn_ingresar.setBackground(Color.white);
    }//GEN-LAST:event_Btn_ingresarMouseExited

    private void Input_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Input_UsuarioMousePressed
    if (  Input_Usuario.getText().equals("Ingresa tu nombre de usuario")){
        
        Input_Usuario.setText("");
          Input_Usuario.setForeground(Color.white);
        
    }
    if ( String.valueOf(Input_password.getPassword()).isEmpty())  {
     Input_password.setText("********");
       Input_Usuario.setForeground(new Color(204,204,204));
    }
      
     
       
    }//GEN-LAST:event_Input_UsuarioMousePressed

    private void Input_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Input_passwordMousePressed
      
        
         if (String.valueOf(Input_password.getPassword()).equals("********")) {
            Input_password.setText("");
            Input_password.setForeground(Color.white);
        }
        if (Input_Usuario.getText().isEmpty()) {
            Input_Usuario.setText("Ingresa tu nombre de usuario");
            Input_Usuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Input_passwordMousePressed

    private void Input_UsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_UsuarioFocusGained
        if (  Input_Usuario.getText().equals("Ingresa tu nombre de usuario")){
        
        Input_Usuario.setText("");
          Input_Usuario.setForeground(Color.white);
        
    }
    if ( String.valueOf(Input_password.getPassword()).isEmpty())  {
     Input_password.setText("********");
       Input_Usuario.setForeground(new Color(204,204,204));
    }
    }//GEN-LAST:event_Input_UsuarioFocusGained

    private void Input_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_passwordFocusGained
         
         if (String.valueOf(Input_password.getPassword()).equals("********")) {
            Input_password.setText("");
            Input_password.setForeground(Color.white);
        }
        if (Input_Usuario.getText().isEmpty()) {
            Input_Usuario.setText("Ingresa tu nombre de usuario");
            Input_Usuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Input_passwordFocusGained

    private void Btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_ingresar;
    private javax.swing.JTextField Input_Usuario;
    private javax.swing.JPasswordField Input_password;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_clave;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel PanelBarraSuperior;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JSeparator Separador_Calve;
    private javax.swing.JSeparator Separador_usuario;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
