package autentificación.Interfaces;

import autentificación.Interfaces.Menu;
import autentificación.conexion.ingreso;
import autentificación.conexion.logica;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelImagen = new javax.swing.JPanel();
        Btn_Salir = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        PanelForm = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Input_Usuario = new javax.swing.JTextField();
        Separador_usuario = new javax.swing.JSeparator();
        Label_clave = new javax.swing.JLabel();
        Input_password = new javax.swing.JPasswordField();
        Separador_Calve = new javax.swing.JSeparator();
        Btn_ingresar = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo-basico-java-swing");
        setBackground(new java.awt.Color(243, 241, 245));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Frame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(740, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(740, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelImagen.setBackground(new java.awt.Color(255, 255, 255));
        PanelImagen.setForeground(new java.awt.Color(255, 255, 255));

        Btn_Salir.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn_Salir.setForeground(new java.awt.Color(25, 52, 152));
        Btn_Salir.setText("X");
        Btn_Salir.setToolTipText("Cerrar programa");
        Btn_Salir.setBorder(null);
        Btn_Salir.setBorderPainted(false);
        Btn_Salir.setContentAreaFilled(false);
        Btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Salir.setDefaultCapable(false);
        Btn_Salir.setFocusPainted(false);
        Btn_Salir.setFocusable(false);
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autentificación/Imagenes/undraw_book_lover_mkck.png"))); // NOI18N
        imagen.setLabelFor(imagen);
        imagen.setMaximumSize(new java.awt.Dimension(370, 500));
        imagen.setMinimumSize(new java.awt.Dimension(370, 500));
        imagen.setPreferredSize(new java.awt.Dimension(370, 500));

        javax.swing.GroupLayout PanelImagenLayout = new javax.swing.GroupLayout(PanelImagen);
        PanelImagen.setLayout(PanelImagenLayout);
        PanelImagenLayout.setHorizontalGroup(
            PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelImagenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );
        PanelImagenLayout.setVerticalGroup(
            PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(PanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelImagenLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(523, Short.MAX_VALUE)))
        );

        getContentPane().add(PanelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        PanelForm.setBackground(new java.awt.Color(25, 52, 152));
        PanelForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelForm.setPreferredSize(new java.awt.Dimension(370, 500));
        PanelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setText("USUARIO");
        PanelForm.add(Label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Input_Usuario.setBackground(new java.awt.Color(25, 52, 152));
        Input_Usuario.setBorder(null);
        Input_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_UsuarioActionPerformed(evt);
            }
        });
        PanelForm.add(Input_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, -1));

        Separador_usuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelForm.add(Separador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 10));

        Label_clave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_clave.setForeground(new java.awt.Color(255, 255, 255));
        Label_clave.setText("CLAVE");
        PanelForm.add(Label_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Input_password.setBackground(new java.awt.Color(25, 52, 152));
        Input_password.setBorder(null);
        PanelForm.add(Input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, -1));

        Separador_Calve.setBackground(new java.awt.Color(255, 255, 255));
        PanelForm.add(Separador_Calve, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 10));

        Btn_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_ingresar.setForeground(new java.awt.Color(25, 52, 152));
        Btn_ingresar.setText("INGRESAR");
        Btn_ingresar.setBorder(null);
        Btn_ingresar.setBorderPainted(false);
        Btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ingresarActionPerformed(evt);
            }
        });
        PanelForm.add(Btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 30));

        TITULO.setBackground(new java.awt.Color(255, 255, 255));
        TITULO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("INICIO DE SESIÓN");
        PanelForm.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        getContentPane().add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("Ejemplo basico e java swing  en cual se realiza una conexion con una base de datos mysql ,un sencillo login , un crud para crear y eliminar alumnos, una sencilla calculadora y un apartado para calcula la circunferencia y una calculadora sencilla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
System.exit(0);

        
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ingresarActionPerformed
    ResultSet rs=null;
    String user="";
    String pass="";
    
        String usuario =this.Input_Usuario.getText();
        String clave = String.valueOf(this.Input_password.getPassword());
         logica conec=new logica();    
        String sql ="select * from usuario where usuario='"+usuario+"' and  clave ='"+clave+"'";
        
        try {
            rs=conec.ConsultaGeneralSQL(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs.next())//si existan datos
            {
                user=rs.getString(2);
                pass=rs.getString(3);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        ingreso ingreso= new ingreso();
        if
                (usuario.equalsIgnoreCase(user)  && clave.equalsIgnoreCase(pass))
        {
            Menu menu = new Menu();
            menu.setVisible(true);
        }
        else
        {
                JOptionPane.showMessageDialog(this,"usuario o clave incorrectos");
        }
        
    }//GEN-LAST:event_Btn_ingresarActionPerformed

    private void Input_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_ingresar;
    private javax.swing.JTextField Input_Usuario;
    private javax.swing.JPasswordField Input_password;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JLabel Label_clave;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JSeparator Separador_Calve;
    private javax.swing.JSeparator Separador_usuario;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
